#服务器端口配置
Server:
  port: 8080

#数据库配置
spring:
  datasource:
    username: root
    password: 123456
    # 报错设置时间
    url: jdbc:mysql://117.72.73.41:3306/onlinebookstore?serverTimezone=UTC&useUnicode&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    basename: i18n.login, i18n.register
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false

#mybatis配置
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.god.entity
